### ISSUE TITLE
append coordinates?

### ISSUE THREAD

**Issue by qoqoh** [imlab-uiip/lung-segmentation-3d#4]
hi. eclique. i do not understand  your code about appending coordinates (i cut the code from this Repository). because i think xx and yy should exchange their coordinates. could you please tell me why do you do that? why not xx[i, :, :, 0] = i and yy[:, i, :, 0] = i   ? 
    if append_coord:
        n = X.shape[0]
        inpShape = X.shape[1:]
        xx = np.empty(inpShape)
        for i in xrange(inpShape[1]):
            xx[:, i, :, 0] = i
        yy = np.empty(inpShape)
        for i in xrange(inpShape[0]):
            yy[i, :, :, 0] = i
        zz = np.empty(inpShape)
        for i in xrange(inpShape[2]):
            zz[:, :, i, 0] = i
        X = np.concatenate([X, np.array([xx] * n), np.array([yy] * n), np.array([zz] * n)], -1)

**Comment by eclique** [comment]
Hi @qoqoh,
The reason why there's an option to append coordinates is the following. It tries to incorporate the spatial information into the input. So the network will see not only the pixel intensity but also, explicitly, its location (x, y, z). This might help because the diversity in lung masks location is not too high, so the location of a point has some information of how likely it will be a lung.
Concerning x and y swapped: in numpy first coordinate is row number. But it doesn't really matter in this case, it's all symmetric.
