### ISSUE TITLE
what's the effect of 'append_coords' in dataload.py

### ISSUE THREAD

**Issue by ahuczp** [imlab-uiip/lung-segmentation-3d#6]
Hey, many thanks to you. I have read your code ,I can not understand the effect of the parameter ‘append_coords’ in dataload.py. Can you tell me how to use this paramater.

**Comment by eclique** [comment]
Hi @ahuczp,

Let I(x,y,z) be the intensity value at coordinates x,y,z.
If append_coords is true, than from image I we construct image T, such that T(x,y,z)={I(x,y,z), x, y, z}. T is still 3D, it will just have 4 channels instead of 1, as in I.

The motivation for that is to give the network explicit information about the coordinates. For pixel (0,0,0) we can tell that there can be no lung tissue even without looking at the image, so that information helps. Similarly for more central pixels, the probability of lung tissue there should be higher just because they are close to the center.

So if you want to try this trick set `append_coords = True`, otherwise keep it `False`.
